version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building React app...
      - npm run build || { echo "React build failed"; exit 1; }
      - echo Build complete.
      - ls -la build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync build/ s3://my-react-website-12 --delete --debug

artifacts:
  files:
    - '**/*'
  base-directory: build

