version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building React app...
      - npm run build || { echo "React build failed"; exit 1; }
      - echo Build complete.
      - ls -la build
  post_build:
    commands:
      - echo Checking if build folder exists...
      - ls -la build || { echo "Build folder not found!"; exit 1; }
      - echo Verifying S3 bucket...
      - aws s3 ls s3://my-react-site-123 || { echo "S3 bucket does not exist!"; exit 1; }
      - echo Deploying to S3...
      - aws s3 sync build/ s3://my-react-website-12 --delete --debug

artifacts:
  files:
    - '**/*'
  base-directory: build


