version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - aws --version  # Show AWS CLI version
      - aws configure list  # Confirm available credentials

  build:
    commands:
      - echo "Building React app..."
      - npm run build || { echo "React build failed"; exit 1; }
      - echo "Contents of build/:"
      - ls -la build

  post_build:
    commands:
      - echo "Validating build folder presence..."
      - ls -la build || { echo "Build folder not found!"; exit 1; }
      - echo "Checking S3 bucket existence..."
      - aws s3 ls s3://my-react-website-12 || { echo "S3 bucket not found!"; exit 1; }
      - echo "Testing bucket write permissions..."
      - echo test > test-file.txt
      - aws s3 cp test-file.txt s3://my-react-website-12/ && \
        echo "Write permission OK" || echo "Write permission failed"
      - echo "Syncing build/ to S3..."
      - aws s3 sync build/ s3://my-react-website-12 --delete --debug
      - echo "Removing test file from bucket..."
      - aws s3 rm s3://my-react-website-12/test-file.txt || echo "Failed to remove test file"

artifacts:
  files:
    - '**/*'
  base-directory: build

  files:
    - '**/*'
  base-directory: build


